# Generated by Django 4.1.7 on 2023-03-21 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafes_order_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='student_class',
        ),
        migrations.AddField(
            model_name='mentor',
            name='school',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cafes_order_list.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentclass',
            name='mentor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cafes_order_list.mentor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentorder',
            name='auto_order',
            field=models.BooleanField(default=False, verbose_name='auto ordering'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes_order_list.studentclass'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes_order_list.school'),
        ),
        migrations.AlterField(
            model_name='studentorder',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes_order_list.student'),
        ),
        migrations.CreateModel(
            name='Bartender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30, verbose_name='surname')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes_order_list.school')),
            ],
        ),
    ]
